docs/.wordlist.txt
docs/how-to/index.md
docs/how-to/integrate_sdcore_with_external_gnb.md

Adds a howto explaining deployment of a gNB Integrator with an existing charmed aether installation.

feat: Add gNB Integrator Howto

---

docs/tutorials/getting_started.md
docs/tutorials/mastering.md
examples/terraform/getting_started/terraform.tf
examples/terraform/mastering/terraform.tf

Allows using Juju Terraform provider versions >= 0.11.0

fix: Fix juju provider version

---

docs/.wordlist.txt
docs/how-to/deploy_sdcore_user_plane_in_dpdk_mode.md
docs/how-to/index.md

The implementation of the DPDK support in the UPF has been introduced in https://github.com/canonical/sdcore-upf-operator/pull/57. 
However, documentation of this feature was missing.
Hence, this PR adds a how-to about using UPF in DPDK mode.

feat: Adding a how-to for deploying UPF in DPDK mode

---

docs/tutorials/mastering.md
terraform/gnbsim-network-config.yml
terraform/main.tf
terraform/user-plane-network-config.yml

This PR adds a Terraform module that deploys the required infrastructure to run the mastering tutorial. At the same time, it simplifies the setup by using LXD directly and using advanced features, like the automatic DNS on managed bridge networks.
The tutorial itself is simplified a lot and should be easier to run for users, with less chance for errors.
The Terraform module could also be reused for testing different scenarios.
**Known issues:**
- There is a race condition adding the SSH keys to the machines related to cloud-init execution. Retrying the `terraform apply` seems to work consistently.

feat: Update mastering tutorial to use Infrastructure as Code

---

terraform/main.tf

- Fixes https://github.com/canonical/charmed-aether-sd-core/issues/21
- Gnbsim VM networking is configured properly within this PR.

fix: Use ethx naming for NIC devices

---

docs/how-to/deploy_sdcore_cups.md
docs/how-to/deploy_sdcore_standalone.md
docs/how-to/deploy_sdcore_user_plane_in_dpdk_mode.md
docs/how-to/integrate_sdcore_with_external_gnb.md
docs/how-to/integrate_sdcore_with_observability.md
docs/reference/deployment_options.md
docs/tutorials/accelerated_networking.md
docs/tutorials/getting_started.md
docs/tutorials/mastering.md
examples/terraform/getting_started/main.tf
examples/terraform/mastering/main.tf

This PR updates the name of the repository containing SD-Core root modules. We're loosing the `-k8s` suffix, because the repo will also hold the root module for the machine charm.
NOTE:
The repo hasn't been renamed yet, so please don't merge this PR.

chore: Updates the name of the repository containing SD-Core root modules

---

docs/how-to/deploy_sdcore_user_plane_in_dpdk_mode.md
terraform/main.tf

Adds how-to for deploying UPF machine charm in DPDK mode. 
To avoid creating new How-to, the existing DPDK doc will now have tabs describing configuration steps for both the K8s charm and the machine charm.

chore: Adds how-to for deploying UPF machine charm in DPDK mode

---

docs/.wordlist.txt
docs/reference/deployment_options.md

Clarify the differences between the K8s and machine deployment options for the UPF charm.

docs: upf k8s vs machine deployment options

---

.github/pull_request_template.md
CONTRIBUTING.md

Here we link to Canonical Documentation style guide which should be followed for all documentation.
- https://docs.ubuntu.com/styleguide/en

chore: link to Canonical style guide

---

docs/how-to/integrate_sdcore_with_observability.md

Adds missing double quotes around the COS URL.

fix: Fixes the source url of the COS module

---

docs/how-to/deploy_sdcore_cups.md
docs/how-to/deploy_sdcore_gnbsim.md
docs/how-to/deploy_sdcore_standalone.md
docs/how-to/deploy_sdcore_user_plane_in_dpdk_mode.md
docs/how-to/troubleshoot_deployment_issues.md
docs/how-to/troubleshoot_user_plane_issues.md
docs/tutorials/accelerated_networking.md
docs/tutorials/getting_started.md
docs/tutorials/mastering.md

Use Juju 3.5 and Microk8s 1.31.
Replace Remove Juju controller link as link check fails with the previous one.

chore: use Juju 3.5 in the documentation

---

docs/tutorials/getting_started.md
docs/tutorials/mastering.md

This PR updates the tutorials to specify that the external address returned by traefik is `https` instead of `http`, after the TLS integration was added to the NMS.

docs: use https to access the NMS

---

docs/how-to/backup_sdcore.md
docs/how-to/restore_sdcore.md
docs/tutorials/getting_started.md

This PR sets the the `6/stable` channel for mongodb charm instead of `6/beta`

chore: move to channel 6/stable in mongodb

---

docs/.wordlist.txt
docs/reference/index.md
docs/reference/user_management.md
docs/tutorials/getting_started.md
docs/tutorials/mastering.md

Now we have authentication for the NMS. This PR add the steps to login to the tutorials  and a reference for user management.
To retrieve the username and password we need to reveal the juju secret associated to the NMS application.

docs: add login step to tutorials

---

docs/explanation/security.md
docs/how-to/deploy_sdcore_gnbsim.md
docs/how-to/integrate_sdcore_with_external_gnb.md
docs/how-to/troubleshoot_user_plane_issues.md
docs/tutorials/getting_started.md
docs/tutorials/mastering.md
examples/terraform/getting_started/main.tf
examples/terraform/getting_started/ran.tf
examples/terraform/mastering/main.tf

Update the documentation for the 1.5 release. This involves:
- Updating the URLs for Terraform modules to point to the release
- Updating the example juju status outputs to match
- Remove the OCI images size comparison as this is not true anymore 
This depends on the following PRs being merged, in this order:
1. https://github.com/canonical/sdcore-upf-k8s-operator/pull/435
2. https://github.com/canonical/sdcore-gnbsim-rock/pull/31
3. https://github.com/canonical/sdcore-gnbsim-k8s-operator/pull/366
Once those are merged, the UPF and GNBSIM charms will need to be promoted to stable.

chore: Update documentation for 1.5 release

---

docs/how-to/deploy_sdcore_gnbsim.md
docs/how-to/deploy_sdcore_standalone.md
docs/how-to/deploy_sdcore_user_plane_in_dpdk_mode.md
docs/how-to/troubleshoot_deployment_issues.md
docs/how-to/troubleshoot_user_plane_issues.md
docs/tutorials/getting_started.md
docs/tutorials/mastering.md

Bump juju to the latest stable release: `3.6/stable`

docs: bump juju version to 3.6/stable

---

docs/tutorials/getting_started.md

Traefik initial error message is `hook failed: "ingress-relation-created`. Updating this in the tutorial.

chore: update traefik unit initial error message

---

docs/how-to/deploy_sdcore_user_plane_in_dpdk_mode.md
docs/how-to/integrate_sdcore_with_observability.md
docs/tutorials/accelerated_networking.md
docs/tutorials/mastering.md

I noticed that the documentation on v1.5 was somehow missing some `refs` in the Terraform URLs, making the user deploy the development version instead of the intended stable 1.5 release.
This adds all missing `refs` to the modules URLs.

fix: Add missing v1.5 refs in v1.5 documentation

---

docs/how-to/integrate_sdcore_with_external_gnb.md
docs/tutorials/accelerated_networking.md
docs/tutorials/getting_started.md
docs/tutorials/mastering.md
examples/terraform/getting_started/core.tf
examples/terraform/getting_started/ran.tf
examples/terraform/mastering/main.tf
terraform/main.tf

- Replaces `fiveg_gnb_identity` with `fiveg_core_gnb`
- Removes references to `v1.5` release branch
- Fixes `not a snap cgroup` issue when accessing lxc machines
- Bumps version of the `terraform-lxd` provider to the latest one

feat: Updates documentation after switching from fiveg_gnb_identity to fiveg_core_gnb

---

.github/workflows/automatic-check.yml

This change makes the CI trigger only on PR events, and not on push. This will prevent duplicate runs of CI jobs.

fix: remove duplicate ci jobs

---

docs/.wordlist.txt
docs/how-to/test_upf_performance.md

The existing how-to guide on running performance tests only validated uplink throughput. Here we add a validation for the downlink throughput. 
We also leverage this opportunity to address a minor issue with exec into the vm's.

docs: separate uplink and downlink performance tests

---

docs/tutorials/getting_started.md
docs/tutorials/mastering.md

This is a backport of https://github.com/canonical/charmed-aether-sd-core/pull/77 and https://github.com/canonical/charmed-aether-sd-core/pull/80 
This is a fix for https://github.com/canonical/charmed-aether-sd-core/issues/74 and https://github.com/canonical/charmed-aether-sd-core/issues/75

fix: backport small fixes in tutorials

---

docs/tutorials/mastering.md

https://github.com/canonical/charmed-aether-sd-core/issues/75 is not an actual problem but the phrasing can be confusing. This PR clarifies the step.

fix: fix AMF IP manual set in mastering tutorial

---

docs/tutorials/mastering.md

https://github.com/canonical/charmed-aether-sd-core/issues/75 is not an actual problem but the phrasing can be confusing. This PR clarifies the step.

fix: backport clarification on mastering tutorial

---

docs/tutorials/getting_started.md
docs/tutorials/mastering.md

After releasing new version of Traefik to stable, the note about Traefik's bug is no longer needed.

chore: Removes note about Traefik's bug

---

docs/.wordlist.txt
docs/reference/performance.md

Here I re-structure the Performance reference so that results are at the top as those are likely what users will care the most about.
I added results from the AF_PACKET runs with different CNIs.

docs: add af_packet performance results

---

docs/tutorials/getting_started.md

fix: typo in starting tutorial

fix: typo in starting tutorial

---

docs/.wordlist.txt
docs/reference/index.md
docs/reference/testing.md

During a discussion with @solmyrcan , he mentioned that a potential user would be interested in knowing more about how we test our solution. This document provides a reference on the various types of tests that are performed on Charmed Aether SD-Core.

docs: add reference on testing

---

docs/.wordlist.txt
docs/reference/performance.md

Here we add test results for the number of subscribers as obtained through UERANSIM. UERANSIM supports up to 500 concurrent PDU sessions and we were able to go up to that limit. Further testing would be needed to validate what's the absolute limit of the core, but the fact that it's at least 500 is already useful information.
Running ueransim for more than 1 UE is quite simple with the `-n` flag. It will incremente the imsi by 1 for each additional subscriber and use the same opc and key:
```shell
/usr/bin/nr-ue -c /etc/ueransim/ue.yaml -n 500
```
Here is the run output:
- [ueransim_500.txt](https://github.com/user-attachments/files/18720747/ueransim_500.txt)
You can then use any of those PDU sessions to access the internet:
```shell
root@ueransim-k8s-0:/# ping -I uesimtun156 8.8.8.8 -c 4 …
```

docs: add number of subscribers test result to documentation

---

docs/how-to/test_upf_performance.md
docs/tutorials/mastering.md
examples/terraform/mastering/main.tf
terraform/main.tf

Here, we replace `.mgmt` with `.mgmt.local`. This change is required because of a recent change in the webconsole where we do input validation on the upf hostname and `.mgmt` is not a valid domain.
This PR partly addresses the issue identified here:
- https://github.com/canonical/sdcore-nms-k8s-operator/issues/441

chore: replace domain from .mgmt to .mgmt.local

---

docs/how-to/deploy_sdcore_cups.md

This PR addresses comments from #88. It also updates the TF snippets to match the official modules.

chore: Updates deploy_sdcore_cups.md

---

docs/reference/components.md

We update the component documentation as we updated the minor version of some charm workloads. This PR depends on the following PR's being merged first:
- https://github.com/canonical/sdcore-ausf-k8s-operator/pull/410
- https://github.com/canonical/sdcore-nssf-k8s-operator/pull/407
- https://github.com/canonical/sdcore-pcf-k8s-operator/pull/414
- https://github.com/canonical/sdcore-udm-k8s-operator/pull/397

chore: bump to latest workload versions

---

docs/tutorials/getting_started.md

When we are not using the gnbsim default values for the subscriber, we need to set the imsi, opc, key and sequence number in the gnbsim config
This PR adds this steps to the getting started tutorial

fix:  add subscriber set up before simulation in getting started tutorial

---

docs/tutorials/mastering.md

When we are not using the gnbsim default values for the subscriber, we need to set the imsi, opc, key and sequence number in the gnbsim config
This PR adds this steps to the matering tutorial

fix: add subscriber set up before simulation in mastering tutorial 

---

docs/.wordlist.txt
docs/explanation/hardening.md
docs/explanation/index.md
docs/explanation/security.md

The security section is expanded by mentioning about Access Control and secure Communication in NMS, Database Security, Input Validation, Log Confidentiality and Secure Dependencies.
Besides, a hardening guide is added which recommends to harden Infrastructure and Containerized Applications. In addition, the operational hardening sections advises to use COS stack to visualize the unusual activities or potential security breaches.
There is not an applicable hardening method for Charmed Aether SD-Core in application level for the moment. In this area, a potential feature is being proposed: https://warthogs.atlassian.net/jira/software/c/projects/TELCO/boards/1079/backlog?selectedIssue=TELCO-1707.

feat: expand security documentation

---

docs/reference/components.md
docs/tutorials/getting_started.md
examples/terraform/getting_started/core.tf
examples/terraform/getting_started/ran.tf

UPF charm started to set IP masquerade on the core interface within this [PR](https://github.com/canonical/sdcore-upf-k8s-operator/pull/67). After UPF started to support NATting, router is unnecessary for SD-Core deployments. Hence, this PR removed the router deployment as it has no effect now.

chore: remove router from sdcore deployment

---

docs/tutorials/getting_started.md
docs/tutorials/mastering.md

This PR removes the reference to Sequence Number in `Getting Started` and `Mastering` tutorials, according to https://github.com/canonical/sdcore-gnbsim-k8s-operator/pull/413.

chore: remove Sequence Number from tutorials

---

docs/tutorials/getting_started.md
examples/terraform/getting_started/core.tf
examples/terraform/getting_started/versions.tf

This PR fixes the `Getting Started` tutorial by bringing the `sdcore-router` back to the picture.

fix: Restores router in the Getting started tutorial

---

docs/tutorials/getting_started.md
docs/tutorials/mastering.md

Use TF modules for setting gnbsim config in tutorials.

fix: perform configuration with terraform modules

---

README.md
docs/index.md

Add deprecation notice to let users know that we are deprecating Charmed Aether SD-Core.

docs: add deprecation notice
